name: Publish on Space

on:
  push:
    branches: [ master, publish_* ]

jobs:
  publish:
    name: publish on space
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SetUp Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Add properties and publish
        run: |
          echo projectorClientGroup=org.jetbrains.projector >> gradle.properties
          echo version=$(echo ${{ github.sha }} | head -c 8) >> projector-plugin/gradle.properties
          echo version=$(echo ${{ github.sha }} | head -c 8) >> projector-server/gradle.properties
          ./gradlew clean publish -PmavenUsername=${{ secrets.SPACE_NAME }} -PmavenPassword=${{ secrets.SPACE_TOKEN }}
